server:
  port: ${PORT:8082}

spring:
  application:
    name: msvc-tracks
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/${DB_DATABASE:db_users_springboot}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:sasa}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

