version: "3.9"
services:

  msvc-security:
    container_name: msvc-security
    image: educacionta/msvc-security:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-security/Dockerfile
    ports:
      - "9100:9100"
#    env_file:
#      - ./msvc-security/.env
    environment:
      PORT: 9100
      DB_HOST: db-insidesound-aws.ctuv5cthsaol.us-east-1.rds.amazonaws.com:3306
      DB_USERNAME: admin
      DB_PASSWORD: sasa4321
      DB_DATABASE: db_users_springboot
      ALBUMS_URL: msvc-albums:8081
      TRACKS_URL: msvc-tracks:8082
    networks:
      - spring
    restart: always

  msvc-albums:
    container_name: msvc-albums
    image: educacionta/msvc-albums:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-albums/Dockerfile
    ports:
      - "8081:8081"
#    env_file:
#      - ./msvc-albums/.env
    environment:
      PORT: 8081
      DB_HOST: db-insidesound-aws.ctuv5cthsaol.us-east-1.rds.amazonaws.com:3306
      DB_USERNAME: admin
      DB_PASSWORD: sasa4321
      DB_DATABASE: db_users_springboot
      TRACKS_URL: msvc-tracks:8082
    networks:
      - spring
    restart: always

  msvc-tracks:
    container_name: msvc-tracks
    image: educacionta/msvc-tracks:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-tracks/Dockerfile
    ports:
      - "8082:8082"
#    env_file:
#      - ./msvc-tracks/.env
    environment:
      PORT: 8082
      DB_HOST: db-insidesound-aws.ctuv5cthsaol.us-east-1.rds.amazonaws.com:3306
      DB_USERNAME: admin
      DB_PASSWORD: sasa4321
      DB_DATABASE: db_users_springboot
      ALBUMS_URL: msvc-albums:8081
    networks:
      - spring
    restart: always

#  gateway:
#    container_name: gateway
##    image: educacionta/gateway:latest
#    build:
#      context: ./
#      dockerfile: ./gateway/Dockerfile
#    ports:
#      - "8090:8090"
##    env_file:
##      - ./gateway/.env
#    environment:
#      PORT: 8090
#    networks:
#      - spring
#    depends_on:
#      - msvc-security
#      - msvc-albums
#      - msvc-tracks
#    restart: always

networks:
  spring:
    name: spring