version: "3.9"
services:
  eureka-server:
    container_name: eureka-server
    image: educacionta/eureka-server:latest
#    build:
#      context: ./
#      dockerfile: ./eureka-server/Dockerfile
    ports:
      - "8761:8761"
#    env_file: ./eureka-server/.env
    environment:
      PORT: 8761
    networks:
      - spring
    restart: always

  msvc-security:
    container_name: msvc-security
    image: educacionta/msvc-security:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-security/Dockerfile
    ports:
      - "9100:9100"
#    env_file:
#      - ./msvc-security/.env
    environment:
      PORT: 9100
      DB_HOST: db-insidesound-aws.ctuv5cthsaol.us-east-1.rds.amazonaws.com:3306
      DB_USERNAME: admin
      DB_PASSWORD: sasa4321
      DB_DATABASE: db_users_springboot
      ALBUMS_URL: ec2-23-22-197-89.compute-1.amazonaws.com:8081
      TRACKS_URL: ec2-23-22-197-89.compute-1.amazonaws.com:8082
      EUREKA_URL: http://eureka-server:8761/eureka/
    networks:
      - spring
    depends_on:
      - eureka-server
    restart: always


networks:
  spring:
    name: spring