apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      role: gateway
  template:
    metadata:
      labels:
        role: gateway
    spec:
      containers:
        - name: gateway
          image: educacionta/gateway:latest
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    role: gateway