server:
  port: ${PORT:9100}
msvc:
  tracks:
    url: ${TRACKS_URL:http://localhost:8082}
  albums:
    url: ${ALBUMS_URL:http://localhost:8081}
spring:
  application:
    name: msvc-security
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/${DB_DATABASE:db_users_springboot}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:sasa}
#    url: jdbc:mysql://db-insidesound-aws.ctuv5cthsaol.us-east-1.rds.amazonaws.com:3306/db_users_springboot
#    username: admin
#    password: sasa4321
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
logging:
  level:
    org:
      hibernate:
        SQL: debug
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

#management:
#  tracing:
#    sampling:
#      probability: 1.0


