server:
  port: ${PORT:8090}

spring:
  application:
    name: gateway
  cloud:
    load balancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

#management:
#  tracing:
#    sampling:
#      probability: 1.0