server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    load balancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
management:
  tracing:
    sampling:
      probability: 1.0


eureka:
  instance:
    prefer-ip-address: true