server:
  port: ${PORT:8090}

spring:
  application:
    name: gateway
  cloud:
    load balancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

