server:
  port: ${PORT:8081}
spring:
  application:
    name: insidesound-backend
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/${DB_DATABASE:db_insidesound}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:sasa}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
#Este fija el tamaño del request permitido por tomcat, se configura superior a los limites validados
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org:
      hibernate:
        SQL: debug

pagination:
  default-size: 5

#http://localhost:${PORT:8081}/swagger-ui/index.html
openapi:
  version: v1.0

errorMessages:
  userExists: "El username ya existe"
  emailExists: "El email ya existe"
  titleExists: "El titulo ya existe"
  integrityError: "Error de integridad de datos: %s"

fileValidationMessages:
  nullOrEmpty: "No puede ser nulo ni estar vacio"
  sizeExceeded: "Excede su tamaño maximo de %s bytes"






