server:
  port: ${PORT:8081}
spring:
  application:
    name: insidesound-backend
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/${DB_DATABASE:db_insidesound}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:sasa}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
logging:
  level:
    org:
      hibernate:
        SQL: debug

pagination:
  default-size: 5



